version: "3.9"

services:
  # ===== BACKEND =====
  market_backend:
    container_name: market_backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    networks:
      - market_lesh
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ===== POSTGRES =====
  postgres:
    image: postgres:17-alpine
    container_name: market_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - market_lesh
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${POSTGRES_PORT}:5432"

  # ===== ADMINER =====
  adminer:
    image: adminer:latest
    container_name: market_adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - market_lesh
    restart: unless-stopped
    ports:
      - "8081:8080"

  # ===== MINIO =====
  minio:
    image: minio/minio
    container_name: market_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    networks:
      - market_lesh
    restart: unless-stopped
    ports:
      - "${MINIO_PORT}:9000"
      - "9001:9001"

  # ===== MINIO MC / SETUP =====
  minio-setup:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - market_lesh
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      mc alias set myminio http://${MINIO_HOST}:${MINIO_PORT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      mc mb myminio/processors || true;
      mc mb myminio/users || true;
      mc mb myminio/products || true;
      "

volumes:
  postgres_data:
  minio_data:

networks:
  market_lesh:
    driver: bridge
